In [2]:
# 读取原有文件进行数据分析
import pandas as pd
origin_file_path = '/tmp/pycharm_project_946/dataset/CiteULike/CiteULike/all.csv'
df = pd.read_csv(origin_file_path)

In [4]:
df.shape

(204986, 2)

In [5]:
df

        user   item
0        215      0
1        996      0
2       1448      0
3       1757      0
4       1850      0
...      ...    ...
204981  2728  16971
204982  3525  16971
204983  4592  16971
204984  5018  16971
204985  5537  16971

[204986 rows x 2 columns]

In [6]:
user_counts = df['user'].value_counts()
item_counts = df['item'].value_counts()

# 过滤掉交互次数不足10次的user和item
filtered_df = df[df['user'].isin(user_counts[user_counts >= 10].index) & df['item'].isin(item_counts[item_counts >= 10].index)]

# 返回过滤后的df
print(filtered_df)

        user   item
0        215      0
1        996      0
2       1448      0
3       1757      0
4       1850      0
...      ...    ...
204966  4285  16947
204967  4592  16947
204968  4943  16947
204969  5026  16947
204970  5249  16947

[144806 rows x 2 columns]

In [8]:
filtered_df = filtered_df.reset_index(drop=True)

In [9]:
filtered_df

        user   item
0        215      0
1        996      0
2       1448      0
3       1757      0
4       1850      0
...      ...    ...
144801  4285  16947
144802  4592  16947
144803  4943  16947
144804  5026  16947
144805  5249  16947

[144806 rows x 2 columns]

In [10]:
# 对 user 列进行重新编码
filtered_df['user'] = pd.factorize(filtered_df['user'])[0]

# 对 item 列进行重新编码
filtered_df['item'] = pd.factorize(filtered_df['item'])[0]

# 返回重新编码后的df
print(filtered_df)

        user  item
0          0     0
1          1     0
2          2     0
3          3     0
4          4     0
...      ...   ...
144801  5514  7848
144802   442  7848
144803   116  7848
144804  1907  7848
144805   998  7848

[144806 rows x 2 columns]

In [11]:
filtered_df.to_csv('/tmp/pycharm_project_946/dataset/CiteULike/CiteULike/CiteULike.inter', index=False)

In [12]:
filtered_df['rating'] = 1

In [13]:
filtered_df

        user  item  rating
0          0     0       1
1          1     0       1
2          2     0       1
3          3     0       1
4          4     0       1
...      ...   ...     ...
144801  5514  7848       1
144802   442  7848       1
144803   116  7848       1
144804  1907  7848       1
144805   998  7848       1

[144806 rows x 3 columns]

In [14]:
filtered_df.to_csv('/tmp/pycharm_project_946/dataset/CiteULike/CiteULike/CiteULike.csv', index=False, sep='\t')

## 进行冷热数据的分割

In [2]:
import numpy as np
import pandas as pd

# 读取数据
df = pd.read_csv('/Users/yzh/PycharmProjects/RecBole/dataset/CiteULike/CiteULike/CiteULike.inter', sep='\t')